name: dapper
channels:
  - conda-forge
dependencies:
  - geopandas
  - earthengine-api
  - geemap
  - cdsapi>=0.7.7
  - pip
  - xarray
  - cftime
  - tqdm
  - rioxarray
  - jupyter
  - fastparquet
  - netcdf4
  - intake-esm # for Pangeo CMIP access
  - gcsfs # for Pangeo CMIP downloading
  - folium # interactive mapping
  - contextily # static mapping
  - xyzservices # basemaps
  - pytest

