name: dapper
channels:
  - conda-forge
dependencies:
  - geopandas
  - earthengine-api
  - geemap
  - pip
  - xarray
  - cftime
  - tqdm
  - rioxarray
  - jupyter
  - fastparquet
  - netcdf4
  - intake-esm # for Pangeo CMIP access
  - gcsfs # for Pangeo CMIP downloading

