[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dapper-elm"
version = "1.0"
description = "Data Preprocessing for ELM Runs"
authors = [{ name = "Dapper contributors", email = "dapper@lanl.gov" }]
readme = "README.md"
requires-python = ">=3.11"
license = {file = "license.md"}
dependencies = [
  "geopandas",
  "pandas>=3",
  "earthengine-api",
  "geemap",
  "cdsapi>=0.7.7",
  "pip",
  "xarray",
  "cftime",
  "tqdm",
  "rioxarray",
  "jupyter",
  "fastparquet",
  "netcdf4",
  "intake-esm", # for Pangeo CMIP access # for Pangeo CMIP downloading
  "gcsfs",
  "jupytext>=1.19.3",
  "matplotlib>=3.10.9",
  "xyzservices>=2026.3.0",
  "contextily>=1.7.0",
]

[project.urls]
"Homepage" = "https://github.com/NGEE-Arctic/dapper"
"Bug Tracker" = "https://github.com/NGEE-Arctic/dapper/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["dapper", "dapper.*"]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
