"""Characterization tests for Domain construction and ELM domain export (T-1).

These pin current behavior ahead of refactoring. Bug B4 (corner order) has
been fixed; its former pins are now regression tests.
"""

import math

import geopandas as gpd
import numpy as np
import pytest
import xarray as xr
from shapely.geometry import box

from dapper import Domain
from dapper.domains.elm_domain import to_elm_domain_dataset


def _two_cells(frac=(1.0, 0.5)):
    return gpd.GeoDataFrame(
        {"gid": ["a", "b"], "frac": list(frac)},
        geometry=[box(-150, 68, -149.5, 68.5), box(-149.5, 68, -149, 68.5)],
        crs="EPSG:4326",
    )


def test_elm_domain_dataset_layout_and_values():
    dom = Domain.from_provided(_two_cells(), name="dom", mode="cellset")
    ds = to_elm_domain_dataset(dom)

    assert dict(ds.sizes) == {"nj": 2, "ni": 1, "nv": 4}
    np.testing.assert_allclose(ds["xc"].values[:, 0], [-149.75, -149.25])
    np.testing.assert_allclose(ds["yc"].values[:, 0], [68.25, 68.25])
    np.testing.assert_allclose(ds["frac"].values[:, 0], [1.0, 0.5])
    np.testing.assert_array_equal(ds["mask"].values[:, 0], [1, 1])

    expected_area = math.radians(0.5) * (
        math.sin(math.radians(68.5)) - math.sin(math.radians(68.0))
    )
    np.testing.assert_allclose(ds["area"].values[:, 0], [expected_area] * 2)

    # Regression for B4: corners are counter-clockwise (ll, lr, ur, ul).
    np.testing.assert_allclose(ds["xv"].values[0, 0], [-150.0, -149.5, -149.5, -150.0])
    np.testing.assert_allclose(ds["yv"].values[0, 0], [68.0, 68.0, 68.5, 68.5])

    assert ds.attrs == {
        "Conventions": "NCAR-CSM:CF-1.0",
        "title": "ELM domain data: generated by dapper",
        "user_comment": "Domain generated from dapper.Domain(name='dom', mode='cellset')",
    }


def test_elm_domain_mask_from_frac_and_append_attrs():
    dom = Domain.from_provided(_two_cells(frac=(0.0, 0.3)), name="d", mode="cellset")
    ds = to_elm_domain_dataset(dom, append_attrs={"title": "custom", "extra": 1})
    np.testing.assert_array_equal(ds["mask"].values[:, 0], [0, 1])
    assert ds.attrs["title"] == "custom"
    assert ds.attrs["extra"] == 1

    ds_nomask = to_elm_domain_dataset(dom, mask_from_frac=False)
    np.testing.assert_array_equal(ds_nomask["mask"].values[:, 0], [1, 1])


def test_elm_domain_grid_shape_mismatch_raises():
    dom = Domain.from_provided(_two_cells(), name="d", mode="cellset")
    with pytest.raises(ValueError, match="grid_shape"):
        to_elm_domain_dataset(dom, grid_shape=(3, 1))


def test_export_domain_paths_for_cellset_and_sites(tmp_path):
    cellset = Domain.from_provided(
        _two_cells(), name="dom", mode="cellset", path_out=tmp_path
    )
    out = cellset.export_domain()
    assert out == {"dom": tmp_path / "dom" / "domain.nc"}
    assert out["dom"].exists()

    with pytest.raises(FileExistsError):
        cellset.export_domain()

    sites = Domain.from_provided(
        _two_cells(), name="grp", mode="sites", path_out=tmp_path
    )
    out_sites = sites.export_domain()
    assert out_sites == {
        "a": tmp_path / "grp" / "a" / "domain.nc",
        "b": tmp_path / "grp" / "b" / "domain.nc",
    }
    with xr.open_dataset(out_sites["b"]) as ds:
        assert dict(ds.sizes) == {"nj": 1, "ni": 1, "nv": 4}
        assert ds.attrs["user_comment"] == (
            "Domain generated from dapper.Domain(name='b', mode='cellset')"
        )

    custom = sites.export_domain(out_dir=tmp_path / "custom", filename="d.nc")
    assert custom["a"] == tmp_path / "custom" / "a" / "d.nc"


def test_from_elm_domain_round_trip(tmp_path):
    dom = Domain.from_provided(
        _two_cells(), name="dom", mode="cellset", path_out=tmp_path
    )
    path = dom.export_domain()["dom"]

    back = Domain.from_elm_domain(path)
    assert back.name == "domain"
    assert back.mode == "cellset"
    assert back.domain_nc == path
    assert back.cells["gid"].tolist() == ["cell_00000", "cell_00001"]
    np.testing.assert_allclose(back.cells["lon"], [-149.75, -149.25])
    np.testing.assert_allclose(back.cells["frac"], [1.0, 0.5])
    assert back.cells["i"].tolist() == [0, 0]
    assert back.cells["j"].tolist() == [0, 1]
    # Regression for B4: cells read back as valid 0.5 x 0.5 degree boxes.
    assert all(g.is_valid for g in back.cells.geometry)
    np.testing.assert_allclose([g.area for g in back.cells.geometry], [0.25, 0.25])

    thresholded = Domain.from_elm_domain(path, frac_threshold=0.6, name="x")
    assert thresholded.name == "x"
    assert thresholded.cells["gid"].tolist() == ["cell_00000"]


def test_from_file_reprojects_and_names_from_stem(tmp_path):
    gdf = _two_cells().to_crs("EPSG:3413")
    path = tmp_path / "sites.gpkg"
    gdf.to_file(path)

    dom = Domain.from_file(path, mode="sites", path_out=tmp_path)
    assert dom.name == "sites"
    assert dom.mode == "sites"
    assert dom.provided.crs.to_epsg() == 4326
    assert dom.path_out == tmp_path
    assert dom.gids == ["a", "b"]
    np.testing.assert_allclose(dom.cells["lon"], [-149.75, -149.25], atol=1e-6)


def test_from_provided_validation_and_defaults():
    with pytest.raises(ValueError, match="mode="):
        Domain.from_provided(_two_cells())

    single = Domain.from_provided(_two_cells().iloc[[0]], name="one")
    assert single.mode == "cellset"
    assert single.cells.geometry.iloc[0].geom_type == "Polygon"

    dup = _two_cells()
    dup["gid"] = ["x", "x"]
    with pytest.raises(ValueError, match="Duplicate gid"):
        Domain.from_provided(dup, mode="sites")


def test_iter_runs_and_to_df_loc():
    dom = Domain.from_provided(_two_cells(), name="grp", mode="sites")
    runs = list(dom.iter_runs())
    assert [rid for rid, _ in runs] == ["a", "b"]
    run_a = runs[0][1]
    assert run_a.mode == "cellset"
    assert run_a.run_group == "grp"
    assert run_a.cells.geometry.iloc[0].geom_type == "Point"

    df = dom.to_df_loc()
    assert df.columns.tolist() == ["gid", "lon", "lat", "zone", "weight"]
    assert df["zone"].tolist() == [1, 1]
    assert df["weight"].tolist() == [1.0, 0.5]
