"""ELM domain NetCDF utilities."""

from __future__ import annotations

import math
from typing import TYPE_CHECKING

import numpy as np
import xarray as xr

if TYPE_CHECKING:  # pragma: no cover
    from dapper.domains.domain import Domain


def to_elm_domain_dataset(
    domain: "Domain",
    *,
    grid_shape: tuple[int, int] | None = None,
    cell_dx_deg: float = 0.5,
    cell_dy_deg: float | None = None,
    land_frac_col: str | None = "frac",
    mask_from_frac: bool = True,
    append_attrs: dict | None = None,
) -> xr.Dataset:
    """
    Build an ELM land domain Dataset from *cells* (never from support/provided).
    Vertex bounds are always encoded as a 4-corner bounding box (nv=4).
    """
    dom = domain.ensure_cells_lon_lat()
    gdf = dom.cells.copy()
    ncell = len(gdf)
    if ncell == 0:
        raise ValueError("Domain has no cells; cannot build ELM domain.")

    if grid_shape is None:
        nj, ni = ncell, 1
    else:
        nj, ni = grid_shape
        if nj * ni != ncell:
            raise ValueError(f"grid_shape {grid_shape} has nj*ni={nj*ni}, but Domain has {ncell} cells.")

    if cell_dy_deg is None:
        cell_dy_deg = cell_dx_deg

    nv = 4
    area = np.zeros((nj, ni), dtype="f8")
    frac = np.zeros_like(area)
    mask = np.zeros((nj, ni), dtype="i4")
    xc = np.zeros_like(area)
    yc = np.zeros_like(area)
    xv = np.zeros((nj, ni, nv), dtype="f8")
    yv = np.zeros_like(xv)

    if land_frac_col is not None and land_frac_col in gdf.columns:
        frac_vals = gdf[land_frac_col].to_numpy(dtype="f8")
    else:
        frac_vals = np.ones(ncell, dtype="f8")

    for idx, row in gdf.reset_index(drop=True).iterrows():
        j = idx // ni
        i = idx % ni

        lon_c = float(row["lon"])
        lat_c = float(row["lat"])
        geom = row.get("geometry", None)

        if geom is not None and hasattr(geom, "bounds"):
            minx, miny, maxx, maxy = geom.bounds
        else:
            half_dx = cell_dx_deg / 2.0
            half_dy = cell_dy_deg / 2.0
            minx, maxx = lon_c - half_dx, lon_c + half_dx
            miny, maxy = lat_c - half_dy, lat_c + half_dy

        # Bounding-box corners, consistent with existing behavior
        xv[j, i, :] = [minx, maxx, minx, maxx]
        yv[j, i, :] = [miny, miny, maxy, maxy]

        xc[j, i] = lon_c
        yc[j, i] = lat_c

        # radians^2 (same approach as before)
        lam1 = math.radians(minx)
        lam2 = math.radians(maxx)
        phi1 = math.radians(miny)
        phi2 = math.radians(maxy)
        area_sr = (lam2 - lam1) * (math.sin(phi2) - math.sin(phi1))
        if area_sr < 0:
            area_sr = -area_sr
        area[j, i] = area_sr

        fval = float(frac_vals[idx])
        frac[j, i] = fval
        mask[j, i] = 1 if (not mask_from_frac) or fval > 0 else 0

    ds = xr.Dataset(
        coords={"nj": np.arange(nj), "ni": np.arange(ni), "nv": np.arange(nv)},
        data_vars={
            "area": (("nj", "ni"), area),
            "frac": (("nj", "ni"), frac),
            "mask": (("nj", "ni"), mask),
            "xc": (("nj", "ni"), xc),
            "yc": (("nj", "ni"), yc),
            "xv": (("nj", "ni", "nv"), xv),
            "yv": (("nj", "ni", "nv"), yv),
        },
    )

    ds["area"].attrs.update({"long_name": "area of grid cell in radians squared", "coordinate": "xc yc", "units": "radians2"})
    ds["frac"].attrs.update({"long_name": "fraction of grid cell that is active", "coordinate": "xc yc", "units": "unitless"})
    ds["mask"].attrs.update({"long_name": "land domain mask", "coordinate": "xc yc", "comment": "0=ocean and 1=land"})
    ds["xc"].attrs.update({"long_name": "longitude of grid cell center", "units": "degrees_east", "bounds": "xv"})
    ds["xv"].attrs.update({"long_name": "longitude of grid cell vertices", "units": "degrees_east"})
    ds["yc"].attrs.update({"long_name": "latitude of grid cell center", "units": "degrees_north", "bounds": "yv"})
    ds["yv"].attrs.update({"long_name": "latitude of grid cell vertices", "units": "degrees_north"})

    attrs_default = {
        "Conventions": "NCAR-CSM:CF-1.0",
        "title": "ELM domain data: generated by dapper",
        "user_comment": f"Domain generated from dapper.Domain(name='{domain.name}', mode='{domain.mode}')",
    }
    if append_attrs:
        attrs_default.update(append_attrs)
    ds.attrs.update(attrs_default)

    return ds
