name: Mirror
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "$NGEE_PRIVATE" > ngee_private.key
          echo "$NGEE_PRIVATE2" > ngee_private2.key
          chmod 600 ngee_private.key
          chmod 600 ngee_private2.key
          key_location=$(pwd)/ngee_private.key
          key_location2=$(pwd)/ngee_private2.key
          #
          git clone --mirror git@github.com:NGEE-Arctic/dapper.git --config core.sshCommand="ssh -i $key_location"
          cd dapper.git
          git remote set-url --push origin git@github.com:lanl/dapper.git
          git fetch -p origin
          git config --global core.sshCommand "ssh -i $key_location2"
          git push --mirror || true
        env:
            NGEE_PRIVATE: ${{ secrets.NGEE_PRIVATE }}
            NGEE_PRIVATE2: ${{ secrets.NGEE_PRIVATE2 }}
